### ISSUE TITLE
For your repositories Custom-field-types-widgets-and-formatters

### ISSUE THREAD

**Issue by bertrand-kaernel** [sujanshresthanet/Custom-field-types-widgets-and-formatters#1]
Hello. There is a bug in your module. 

The namespace in FieldType, FieldWidget and FieldFormatter is :

`namespace Drupal\custom_fields\Plugin\Field\FieldWidget;`

instead of  : 

`namespace Drupal\custom_field\Plugin\Field\FieldWidget;`

**Comment by sujanshresthanet** [comment]
Hi, Thank you for your feedback! I've reviewed your comments and addressed the issues.
